services:
  db:
    image: mariadb:${MARIADB_VERSION:-10.6}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=${DB_USERNAME:-user}
      - MARIADB_PASSWORD=${DB_PASSWORD:-K65k2rgWT3vDfh8EAzA8}
      - MARIADB_DATABASE=${DB_NAME:-app}

  nginx-php-fpm:
    image: trafex/php-nginx:${TRAFEX_PHP_NGINX_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ":80"
    volumes:
      - ./public_html:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/cloudflare_ips:/etc/nginx/cloudflare_ips
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/php/php.ini:/etc/php81/conf.d/settings.ini
      - ./config/php/php-fpm.d/www.conf:/etc/php8/php-fpm.d/www.conf

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION:-5.2}
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ":80"
    environment:
      - PMA_HOST=db

  ftp:
    # optionally replace username/repo:tag with your name and image details
    image: stilliard/pure-ftpd:latest
    environment:
      PUBLICHOST: ${PUBLIC_HOST:-"s1.hostn.cloud"}
      FTP_USER_NAME: ${FTP_USERNAME:-ftp_user}
      FTP_USER_PASS: ${FTP_PASSWORD:-X5fY9wd5cFpn56HALziD}
      FTP_USER_HOME: "/var/www/html"
      #FTP_USER_UID: 33
      #FTP_USER_GID: 33
    volumes:
      - ./public_html:/var/www/html
      - ./config/ftp:/etc/ssl/private
    ports:
      - target: 21
        published: 21
        protocol: tcp
        mode: host

      # Bind each passive ports to the host
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host

volumes:
  db_data:
