version: '3.8'

services:
  db:
    image: mariadb:${MARIADB_VERSION:-10.6}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=${DB_USERNAME:-user}
      - MARIADB_PASSWORD=${DB_PASSWORD:-K65k2rgWT3vDfh8EAzA8}
      - MARIADB_DATABASE=${DB_NAME:-app}

  nginx-php-fpm:
    image: trafex/php-nginx:${TRAFEX_PHP_NGINX_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ":80"
      - ":443"
    volumes:
      - ./public_html:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/php/php.ini:/etc/php81/conf.d/settings.ini
      - ./config/php/php-fpm.d/www.conf:/etc/php8/php-fpm.d/www.conf

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION:-5.2}
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ":80"
    environment:
      - PMA_HOST=db

volumes:
  db_data:
